# Generated by Django 5.1.2 on 2024-11-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='toponimia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
